tasks:
  - init: |
      git checkout gitpod
      docker run -d -p 8787:8787 -v /workspace:/home/rstudio/workspace -e DISABLE_AUTH=true ghcr.io/lescai-teaching/rstudio-docker-amd64:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8787
    onOpen: open-browser